# -*- coding: utf-8 -*-
"""
Created on Sat Dec  5 13:01:45 2015

@author: hareyakana
"""

import csv
import ternary as t
import pylab as p

"""importing data generated by source flavour"""
onesig110=[]
    
with open('110_1sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        onesig110.append((float(row['x']),float(row['y']),float(row['z'])))

onesig120=[]
    
with open('120_1sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        onesig120.append((float(row['x']),float(row['y']),float(row['z'])))
    
onesig100=[]
    
with open('100_1sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        onesig100.append((float(row['x']),float(row['y']),float(row['z'])))

onesig010=[]
    
with open('010_1sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        onesig010.append((float(row['x']),float(row['y']),float(row['z'])))
       
onesig210=[]
    
with open('210_1sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        onesig210.append((float(row['x']),float(row['y']),float(row['z'])))

###################2sig
twosig110=[]
    
with open('110_2sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        twosig110.append((float(row['x']),float(row['y']),float(row['z'])))

twosig120=[]
    
with open('120_2sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        twosig120.append((float(row['x']),float(row['y']),float(row['z'])))
    
twosig100=[]
    
with open('100_2sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        twosig100.append((float(row['x']),float(row['y']),float(row['z'])))

twosig010=[]
    
with open('010_2sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        twosig010.append((float(row['x']),float(row['y']),float(row['z'])))
       
twosig210=[]
    
with open('210_2sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        twosig210.append((float(row['x']),float(row['y']),float(row['z'])))

##################3sig
threesig110=[]
    
with open('110_3sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        threesig110.append((float(row['x']),float(row['y']),float(row['z'])))

threesig120=[]
    
with open('120_3sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        threesig120.append((float(row['x']),float(row['y']),float(row['z'])))
    
threesig100=[]
    
with open('100_3sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        threesig100.append((float(row['x']),float(row['y']),float(row['z'])))

threesig010=[]
    
with open('010_3sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        threesig010.append((float(row['x']),float(row['y']),float(row['z'])))
       
threesig210=[]
    
with open('210_3sig.txt','r')as f:
    reader = csv.DictReader(f)
    for row in reader:
        threesig210.append((float(row['x']),float(row['y']),float(row['z'])))

"""ternary plot"""
"""ternary plot"""
"""ternary plot"""
figure, d=t.figure(scale=1)

d.boundary(linewidth=2)
d.gridlines(multiple=0.1,color="blue",linewidth=0.8)
#d.gridlines(multiple=0.02,color="green",linewidth=0.2)

d.set_title(r"source flavour composition $\nu_e,\nu_\mu,\nu_\tau$",fontsize=20)
d.left_axis_label(r"$\nu_\tau$",fontsize=20,offset=0.10)
d.right_axis_label(r"$\nu_\mu$",fontsize=20,offset=0.1)
d.bottom_axis_label(r"$\nu_e$",fontsize=20,offset=0.01)
d._redraw_labels()

"""data points"""
point1=[(0.3980599331366308,0.3112164005027349,0.2907236663606344)]
point2=[(0.55214511226237,0.24397475401089158,0.20388013372673847)]
point3=[(0.34669820676138435,0.3336302826666826,0.31967151057193305)]
point4=[(0.24397475401089158,0.3784580469945782,0.3775671989945304)]
democratic=[(1/3,1/3,1/3)]
point5=[(0.4494216595118771,0.2888025183387871,0.26177582214933576)]
ice1=[(0,0.2,0.8)]
ice2=[(0.18,0.41,0.41)]

"""plotting the data points"""
d.ticks(axis='brl',multiple=0.1)
p.axis('off')

d.scatter(threesig120, marker='.', color='#FFA07A', alpha=0.01,s=20)
d.scatter(threesig110, marker='.', color='#B0E0E6', alpha=0.01,s=20)
d.scatter(threesig100, marker='.', color='#EE82EE', alpha=0.01,s=20)
#d.scatter(threesig120, marker='.', color='#FFA07A', alpha=0.01,s=20)
d.scatter(threesig010, marker='.', color='#FFEFD5', alpha=0.01,s=20)
d.scatter(threesig210, marker='.', color='#98FB98', alpha=0.01,s=20)

d.scatter(twosig120, marker='.', color='#CD5C5C', alpha=0.01,s=30)
d.scatter(twosig110, marker='.', color='#00BFFF', alpha=0.01,s=30)
d.scatter(twosig100, marker='.', color='#9370DB', alpha=0.01,s=30)
#d.scatter(twosig120, marker='.', color='#CD5C5C', alpha=0.01,s=30)
d.scatter(twosig010, marker='.', color='#F0E68C', alpha=0.01,s=30)
d.scatter(twosig210, marker='.', color='#32CD32', alpha=0.01,s=30)

d.scatter(onesig120, marker='.', color='#FF0000', alpha=0.01,s=50)
d.scatter(onesig110, marker='.', color='#0000FF', alpha=0.01,s=50)
d.scatter(onesig100, marker='.', color='#6A5ACD', alpha=0.01,s=50)
#d.scatter(onesig120, marker='.', color='#FF0000', alpha=0.01,s=50)
d.scatter(onesig010, marker='.', color='#FFFF00', alpha=0.01,s=50)
d.scatter(onesig210, marker='.', color='#2E8B57', alpha=0.01,s=50)

d.scatter(point1, marker='D', color='#000080', alpha=1, 
          label=r"$(\frac{1}{2},\frac{1}{2},0)$",s=50)
d.scatter(point2, marker='o', color='#663399', alpha=1, 
          label=r"$(1,0,0)$",s=50)
d.scatter(point3, marker='^', color='#8B0000', alpha=1, 
          label=r"$(\frac{1}{3},\frac{2}{3},0)$",s=50)
d.scatter(point4, marker='s', color='#FF4500', alpha=1, 
          label=r"$(0,1,0)$",s=50)
d.scatter(democratic,marker='*',color='black',
          label=r"$(\frac{1}{3},\frac{1}{3},\frac{1}{3})$",s=50)
d.scatter(point5, marker='d',color='#006400',alpha=1,
          label=r"$(\frac{2}{3},\frac{1}{3},0)$",s=50)
d.scatter(ice1, marker='+',label='icecube 1', s=200)
d.scatter(ice2, marker='x',label='icecube 2', s=100)
d.legend()

#d.resize_drawing_canvas(scale=1.15)
d.legend()
d.show()
